FROM node:18-alpine

WORKDIR /app

# Copiar carpeta shared
COPY shared ./shared
WORKDIR /app/shared
RUN npm install

# copiar el backend
WORKDIR /app/backend
COPY backend/package*.json ./
RUN npm ci --only=production

COPY backend ./

EXPOSE 3000

ENV NODE_ENV=production
ENV PORT=3000

CMD ["node", "server.js"]