FROM node:18-alpine

WORKDIR /app

# Copiar carpeta shared
COPY shared ./shared
WORKDIR /app/shared
RUN npm install

# Copiar el products-service
WORKDIR /app/services/products-service
COPY services/products-service/package*.json ./
RUN npm ci --only=production

COPY services/products-service ./

EXPOSE 3002

ENV NODE_ENV=production
ENV PORT=3002

CMD ["node", "server.js"]